[package]
name = "ihexcrc"
version = "0.42.0"
authors = ["knilch <knilch0r@cwde.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4"
